# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3'

services:

  mysql:
    image: mysql:5
    volumes:
    - ./bin/local-dev/mysql:/var/lib/mysql
    - ./bin/local-dev/wordpress/config/mysql/wptests.sql:/docker-entrypoint-initdb.d/wptests.sql
    restart: always
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  wordpress:
    build:
      context: ./bin/local-dev/wordpress
      args:
        WP_VERSION: ${WP_VERSION}
        PHP_VERSION: ${PHP_VERSION}
    depends_on:
      - mysql
    ports:
      - 8088:80
    volumes:
      - ./bin/local-dev/wordpress/html:/var/www/html
      - ./plugin:/var/www/html/wp-content/plugins/material-design
      - ./theme:/var/www/html/wp-content/themes/material-design-google
      # Mount composer files and the vendor folder to both the plugin and theme folders.
      - ./vendor:/var/www/html/wp-content/plugins/material-design/vendor
      - ./composer.json:/var/www/html/wp-content/plugins/material-design/composer.json
      - ./composer.lock:/var/www/html/wp-content/plugins/material-design/composer.lock
      - ./vendor:/var/www/html/wp-content/themes/material-design-google/vendor
      - ./composer.json:/var/www/html/wp-content/themes/material-design-google/composer.json
      - ./composer.lock:/var/www/html/wp-content/themes/material-design-google/composer.lock
    restart: always
    environment:
      WORDPRESS_DEBUG: 1
      WORDPRESS_DB_USER: ${WP_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WP_DB_PASSWORD}

  cli:
    image: wordpress:cli
    user: xfs
    volumes:
      - ./bin/local-dev/wordpress/html:/var/www/html
      - ./plugin:/var/www/html/wp-content/plugins/material-design
      - ./theme:/var/www/html/wp-content/themes/material-design-google
    depends_on:
      - mysql
      - wordpress
    command: tail -f /dev/null

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
